"""Create table charge_observation.

Revision ID: 2154afa58ba0
Revises: 
Create Date: 2020-01-05 12:18:25.331846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2154afa58ba0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charge_observation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charge_observation')
    # ### end Alembic commands ###
