name: testing-tools
channels:
  - conda-forge
dependencies:
  - alembic >= 1.4.0
  - astor >= 0.7.1
  - beautifulsoup4 >= 4.8.2
  - boltons >= 20.0.0
  - cartopy >= 0.17.0
  - click >= 7.0
  - cvxopt >= 1.2.3
  - cython >= 0.29.14
  - dicttoxml >= 1.7.4
  - dill >= 0.3.1.1
  - flake8 >= 3.7.9
  - flask >= 1.1.1
  - folium >= 0.10.1
  - geocoder >= 1.38.1
  - geopy >= 1.21.0
  - html5lib >= 1.0.1
  - isort >= 4.3.21
  - lxml >= 4.5.0
  - matplotlib >= 3.1.2
  - networkx >= 2.4
  - numba >= 0.46.0
  - pandas >= 0.25.3
  - pillow >= 6.1.0
  - pip >= 20.0.2
  - pyarrow >= 0.15.1
  - python == 3.7.3
  - quantities >= 0.12.4
  - requests >= 2.23.0
  - ruamel.yaml >= 0.16.6
  - scikit-learn >= 0.22
  - seaborn >= 0.10.0
  - sqlalchemy >= 1.3.5
  - unyt >= 2.7.1
  - yapf >= 0.28.0
  - pip:
    - colorbrewer >= 0.2.0
    - distlib >= 0.3.0
    - flask-api >= 2.0
    - imgkit >= 1.0.2
    - redis >= 3.4.1
    - sqlacodegen >= 2.1.0
    - tspy >= 0.1.1.1
    - uszipcode >= 0.2.4
