name: testing-tools

channels:
  - conda-forge

dependencies:
  - alembic >= 1.11.1
  - astor >= 0.8.1
  - beautifulsoup4 >= 4.12.2
  - bokeh >= 3.2.0
  - boltons >= 23.0.0
  - cartopy >= 0.20.1
  - click >= 8.1.5
  - colormath >= 3.0.0
  - cvxopt >= 1.3.0
  - cython >= 0.29.24
  - dicttoxml >= 1.7.16
  - dill >= 0.3.6
  - flake8 >= 6.0.0
  - flask >= 2.0.2
  - flask-restx >= 1.0.6
  - folium >= 0.14.0
  - geocoder >= 1.38.1
  - geopy >= 2.3.0
  - glom >= 23.3.0
  - html2text >= 2020.1.16
  - html5lib >= 1.1
  - hypothesis >= 6.81.2
  - ipython >= 8.14.0
  - isort >= 5.12.0
  - jupyter >= 1.0.0
  - lxml >= 4.9.3
  - matplotlib >= 3.6.3
  - more-itertools >= 9.1.0
  - networkx >= 3.1
  - numba >= 0.57.1
  - pandas >= 1.5.3
  - pandas-profiling >= 3.2.0
  - pillow >= 8.4.0
  - pip >= 23.2
  - pyarrow >= 12.0.1
  - pycairo >= 1.24.0
  - python >= 3.10.5
  - python-graphviz >= 0.11.2
  - python.app >= 1.3
  - quantities >= 0.14.1
  - redis-py >= 4.0.2
  - regex >= 2023.6.3
  - requests >= 2.28.2
  - ruamel.yaml >= 0.17.32
  - scikit-learn >= 1.3.0
  - scipy >= 1.9.3
  - seaborn >= 0.12.2
  - spacy >= 3.6.0
  - sqlacodegen >= 2.3.0
  - sqlalchemy < 1.4  # not yet ready for 2.0 changes
  - statsmodels >= 0.13.5
  - streamlit >= 1.24.1
  - svgwrite >= 1.4.3
  - tqdm >= 4.64.1
  - typer >= 0.9.0
  - unyt >= 2.9.5
  - xgboost >= 1.7.4
  - yapf >= 0.33.0
  - pip:
    - colorbrewer >= 0.2.0
    - distlib >= 0.3.7
    - imgkit >= 1.2.3
    - tspy >= 0.1.1.1
    - uszipcode >= 1.0.1
