name: testing-tools

channels:
  - conda-forge

dependencies:
  - alembic >= 1.8.1
  - astor >= 0.8.1
  - beautifulsoup4 >= 4.11.1
  - bokeh >= 2.4.3
  - boltons >= 21.0.0
  - cartopy >= 0.20.1
  - click >= 8.1.3
  - colormath >= 3.0.0
  - cvxopt >= 1.3.0
  - cython >= 0.29.24
  - dicttoxml >= 1.7.4
  - dill >= 0.3.5.1
  - flake8 >= 5.0.4
  - flask >= 2.0.2
  - flask-restx >= 0.5.1
  - folium >= 0.12.0
  - geocoder >= 1.38.1
  - geopy >= 2.2.0
  - glom >= 20.11.0
  - html2text >= 2020.1.16
  - html5lib >= 1.1
  - hypothesis >= 6.47.1
  - ipython >= 8.4.0
  - isort >= 5.10.1
  - jupyter >= 1.0.0
  - lxml >= 4.9.1
  - matplotlib >= 3.5.2
  - more-itertools >= 8.14.0
  - networkx >= 2.8.5
  - numba >= 0.55.2
  - pandas >= 1.4.3
  - pandas-profiling >= 3.2.0
  - pillow >= 8.4.0
  - pip >= 22.2.2
  - pyarrow >= 9.0.0
  - pycairo >= 1.21.0
  - python >= 3.10.5
  - python-graphviz >= 0.11.2
  - python.app >= 1.3
  - quantities >= 0.13.0
  - redis-py >= 4.0.2
  - regex >= 2022.7.25
  - requests >= 2.28.1
  - ruamel.yaml >= 0.17.21
  - scikit-learn >= 1.1.2
  - scipy >= 1.9.0
  - seaborn >= 0.11.2
  - spacy >= 3.4.1
  - sqlacodegen >= 2.3.0
  - sqlalchemy < 1.4  # not yet ready for 2.0 changes
  - statsmodels >= 0.13.2
  - streamlit >= 1.11.1
  - svgwrite >= 1.4.3
  - tqdm >= 4.64.0
  - typer >= 0.4.2
  - unyt >= 2.9.2
  - xgboost >= 1.6.1
  - yapf >= 0.32.0
  - pip:
    - colorbrewer >= 0.2.0
    - distlib >= 0.3.5
    - imgkit >= 1.2.2
    - tspy >= 0.1.1.1
    - uszipcode >= 1.0.1
