name: testing-tools
channels:
  - defaults
  - conda-forge
dependencies:
  - beautifulsoup4
  - click
  - flake8
  - folium
  - html5lib
  - matplotlib
  - pandas
  - pillow
  - quantities
  - requests
  - scikit-learn
  - seaborn
  - sqlalchemy
  - pip:
    - distlib
    - imgkit
    - sqlacodegen
    - uszipcode >= 0.2.0
