name: testing-tools
channels:
  - defaults
  - conda-forge
dependencies:
  - beautifulsoup4 >= 4.7.1
  - boltons >= 19.1.0
  - cartopy >= 0.17.0
  - click >= 7.0
  - flake8 >= 3.7.7
  - flask >= 1.1.1
  - folium >= 0.9.1
  - geocoder >= 1.38.1
  - geopy >= 1.20.0
  - html5lib >= 1.0.1
  - isort >= 4.3.21
  - matplotlib >= 3.1.0
  - pandas >= 0.24.2
  - pillow >= 6.1.0
  - pip >= 19.1.1
  - pyarrow >= 0.14.0
  - python >= 3.7.3
  - quantities >= 0.12.3
  - requests >= 2.21.0
  - scikit-learn >= 0.21.2
  - seaborn >= 0.9.0
  - sqlalchemy >= 1.3.5
  - unyt >= 2.2.2
  - pip:
    - distlib
    - flask-api
    - imgkit
    - sqlacodegen
    - uszipcode >= 0.2.0
