name: testing-tools
channels:
  - defaults
  - conda-forge
dependencies:
  - beautifulsoup4
  - boltons
  - cartopy
  - click
  - flake8
  - flask
  - folium
  - geopy
  - html5lib
  - isort
  - matplotlib
  - pandas
  - pillow
  - pip
  - pyarrow >= 0.12.1
  - quantities
  - requests
  - scikit-learn
  - seaborn
  - sqlalchemy
  - pip:
    - distlib
    - flask-api
    - imgkit
    - sqlacodegen
    - uszipcode >= 0.2.0
