name: testing-tools
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4 >= 4.8.1
  - boltons >= 19.2.0
  - cartopy >= 0.17.0
  - click >= 7.0
  - cvxopt >= 1.2.3
  - flake8 >= 3.7.9
  - flask >= 1.1.1
  - folium >= 0.10.0
  - geocoder >= 1.38.1
  - geopy >= 1.20.0
  - html5lib >= 1.0.1
  - isort >= 4.3.21
  - lxml
  - matplotlib >= 3.1.2
  - networkx >= 2.4
  - pandas >= 0.25.3
  - pillow >= 6.1.0
  - pip >= 19.3.1
  - pyarrow >= 0.15.1
  - python >= 3.7.3
  - quantities >= 0.12.3
  - requests >= 2.22.0
  - ruamel.yaml >= 0.16.5
  - scikit-learn >= 0.21.3
  - seaborn >= 0.9.0
  - sqlalchemy >= 1.3.5
  - unyt >= 2.4.0
  - pip:
    - distlib
    - flask-api
    - imgkit >= 1.0.2
    - sqlacodegen >= 2.1.0
    - tspy >= 0.1.1.1
    - uszipcode >= 0.2.4
