name: testing-tools

channels:
  - conda-forge

dependencies:
  - alembic >= 1.12.1
  - astor >= 0.8.1
  - beautifulsoup4 >= 4.12.2
  - bokeh >= 3.3.1
  - boltons >= 23.0.0
  - cartopy >= 0.20.1
  - click >= 8.1.7
  - colormath >= 3.0.0
  - cvxopt >= 1.3.0
  - cython >= 0.29.24
  - dicttoxml >= 1.7.16
  - dill >= 0.3.7
  - flake8 >= 6.1.0
  - flask >= 2.0.2
  - flask-restx >= 1.2.0
  - folium >= 0.15.0
  - geocoder >= 1.38.1
  - geopy >= 2.4.1
  - glom >= 23.5.0
  - html2text >= 2020.1.16
  - html5lib >= 1.1
  - hypothesis >= 6.91.0
  - ipython >= 8.18.1
  - isort >= 5.12.0
  - jupyter >= 1.0.0
  - lxml >= 4.9.3
  - matplotlib >= 3.6.3
  - more-itertools >= 10.1.0
  - networkx >= 3.2.1
  - numba >= 0.58.1
  - pandas >= 1.5.3
  - pandas-profiling >= 3.2.0
  - pillow >= 8.4.0
  - pip >= 23.3.1
  - pyarrow >= 14.0.1
  - pycairo >= 1.25.1
  - python >= 3.10.5
  - python-graphviz >= 0.11.2
  - python.app >= 1.3
  - quantities >= 0.14.1
  - redis-py >= 4.0.2
  - regex >= 2023.10.3
  - requests >= 2.28.2
  - ruamel.yaml >= 0.18.5
  - scikit-learn >= 1.3.2
  - scipy >= 1.9.3
  - seaborn >= 0.12.2
  - spacy >= 3.7.2
  - sqlacodegen >= 2.3.0
  - sqlalchemy < 1.4  # not yet ready for 2.0 changes
  - statsmodels >= 0.13.5
  - streamlit >= 1.28.2
  - svgwrite >= 1.4.3
  - tqdm >= 4.64.1
  - typer >= 0.9.0
  - unyt >= 2.9.5
  - xgboost >= 1.7.6
  - yapf >= 0.40.1
  - pip:
    - colorbrewer >= 0.2.0
    - distlib >= 0.3.7
    - imgkit >= 1.2.3
    - tspy >= 0.1.1.1
    - uszipcode >= 1.0.1
