name: testing-tools
channels:
  - defaults
  - conda-forge
dependencies:
  - beautifulsoup4
  - click
  - flake8
  - html5lib
  - matplotlib
  - pandas
  - requests
  - scikit-learn
  - sqlalchemy
  - pip:
    - distlib
    - sqlacodegen
    - uszipcode
