name: testing-tools

channels:
  - conda-forge

dependencies:
  - alembic >= 1.7.4
  - astor >= 0.8.1
  - beautifulsoup4 >= 4.10.0
  - bokeh >= 2.4.1
  - boltons >= 21.0.0
  - cartopy >= 0.18.0
  - click >= 7.1.2
  - colormath >= 3.0.0
  - cvxopt >= 1.2.7
  - cython >= 0.29.22
  - dicttoxml >= 1.7.4
  - dill >= 0.3.4
  - flake8 >= 3.9.0
  - flask >= 1.1.1
  - folium >= 0.12.0
  - geocoder >= 1.38.1
  - geopy >= 2.2.0
  - html5lib >= 1.1
  - hypothesis >= 6.24.0
  - isort >= 5.9.3
  - lxml >= 4.6.3
  - matplotlib >= 3.4.3
  - networkx >= 2.6.3
  - numba >= 0.54.1
  - pandas >= 1.2.5
  - pillow >= 6.1.0
  - pip >= 21.3.1
  - pyarrow >= 5.0.0
  - python >= 3.7.8
  - quantities >= 0.12.5
  - requests >= 2.26.0
  - ruamel.yaml >= 0.17.16
  - scikit-learn >= 1.0.1
  - seaborn >= 0.11.2
  - streamlit >= 1.1.0
  - sqlalchemy < 1.4  # not yet ready for 2.0 changes
  - tqdm >= 4.62.3
  - unyt >= 2.8.0
  - yapf >= 0.31.0
  - pip:
    - colorbrewer >= 0.2.0
    - distlib >= 0.3.3
    - flask-api >= 2.0
    - imgkit >= 1.2.2
    - redis >= 3.5.3
    - sqlacodegen >= 2.3.0
    - tspy >= 0.1.1.1
    - uszipcode >= 0.2.6
