name: stores

channels:
  - default
  - conda-forge

dependencies:
  - flake8 >= 3.6.0
  - geopy >= 1.18.1
  - python >= 3.7
  - requests >= 2.21.0
  - sqlalchemy >= 1.2.16
  - sqlite >= 3.26.0
  - pip:
    - uszipcode >= 0.2.2
